name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  repo: documents
  git: git.swablab.de
  url: git.swablab.de/${{ github.repository }}
  token: ${{ secrets.SWABLAB_ORGA_PACKAGE_TOKEN }}

jobs:
  deploy:
    name: deploy
    runs-on: docker
    container:
      image: docker:cli
      env:
        DOCKER_HOST: tcp://172.17.0.1:2375
    steps:
      - name: download
        run: wget -O- https://${{ env.url }}/archive/main.tar.gz | tar -xz

      - name: build
        run: docker buildx build -f ${{ env.repo }}/Containerfile -t ${{ env.url }}:latest ${{ env.repo }}

      - name: login
        run: docker login -u token -p ${{ env.token }} ${{ env.git }}

      - name: push
        run: docker push ${{ env.git }}/${{ github.repository }}:latest
