name: deploy
on: [push, workflow_dispatch]

env:
  STORAGE_DRIVER: vfs

jobs:
  deploy:
    name: deploy
    runs-on: docker
    container:
      image: quay.io/buildah/stable:latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: login
        run: buildah login -u token -p ${{ secrets.SWABLAB_ORGA_PACKAGE_TOKEN }} git.swablab.de

      - name: build
        run: buildah build -t git.swablab.de/${{ github.repository }}:latest ${{ github.server_url }}/${{ github.repository }}.git

      - name: push
        run: buildah push git.swablab.de/${{ github.repository }}:latest
