FROM mcr.microsoft.com/devcontainers/base:alpine
RUN apk add typst font-noto
RUN mkdir -p /usr/share/fonts/ubuntu
RUN wget -O /usr/share/fonts/ubuntu/ubuntu.ttf https://cdn.jsdelivr.net/fontsource/fonts/ubuntu@latest/latin-400-normal.ttf