FROM mcr.microsoft.com/devcontainers/base:alpine
RUN apk add typst
RUN mkdir -p /fonts
RUN wget -O /fonts/ubuntu.ttf https://cdn.jsdelivr.net/fontsource/fonts/ubuntu@latest/latin-400-normal.ttf
RUN wget -O /fonts/noto.ttf https://cdn.jsdelivr.net/fontsource/fonts/noto-sans@latest/latin-400-normal.ttf
ENV TYPST_FONT_PATHS=/fonts