name: Build PDFs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚢 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/build-push-action@v6
        with:
          file: Containerfile
          push: true
          tags: ghcr.io/swablab/documents:latest
