name: Build PDFs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚢 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build containerfile
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/swablab/documents
          tags: latest
          containerfiles: |
            ./Containerfile

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
